{% set name = "stats_arrays" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stats_arrays-{{ version }}.tar.gz
  sha256: 4bc86cd2bcd1bab35954cca87a4ba00327bbcde6df8e11fbfaca1cf365f00904

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - numpy >=1.6.0
    - python >={{ python_min }}
    - scipy >=1.1.0

test:
  imports:
    - stats_arrays
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/brightway-lca/stats_arrays
  summary: Standard NumPy array interface for defining uncertain parameters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://stats-arrays.readthedocs.io/en/latest/
  dev_url: https://github.com/brightway-lca/stats_arrays

extra:
  recipe-maintainers:
    - cmutel
    - xylar
