{% set name = "stats_arrays" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stats_arrays-{{ version }}.tar.gz
  sha256: b1adda2c7e60cea20866050fe5b2f23a625535d03d07835dd0c521a152e8fd27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68.0
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  imports:
    - stats_arrays
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/brightway-lca/stats_arrays
  summary: Standard NumPy array interface for defining uncertain parameters
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: http://stats-arrays.readthedocs.io/en/latest/
  dev_url: https://github.com/brightway-lca/stats_arrays

extra:
  recipe-maintainers:
    - cmutel
    - xylar
