schema_version: 1

context:
  name: stats_arrays
  version: "1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/stats_arrays-${{ version }}.tar.gz
  sha256: 1155d473605351c6d0e0758adce93b0a9dbb0a62ce4bc03a60fdf26aad873716

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=68.0
  run:
    - python >=${{ python_min }}
    - numpy
    - scipy

tests:
  - python:
      imports:
        - stats_arrays
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Standard NumPy array interface for defining uncertain parameters
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/brightway-lca/stats_arrays
  repository: https://github.com/brightway-lca/stats_arrays
  documentation: http://stats-arrays.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cmutel
    - xylar
